[server]
enableCORS = true
enableXsrfProtection = true
headless = true
port = 8501
fileWatcherType = "poll"
folderWatchBlacklist = [
    "/.git/",
    "/.venv/",
    "/venv/",
    "/node_modules/",
    "/__pycache__/",
    "/.mypy_cache/"
]

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#111111"
